"""Geometric mesh validation via injected bmesh snippet.

Used in pipeline phase F3.5 (after StaticAnalyzer). Injects
a bmesh code block at the end of the generated script, executes it
in Blender, and analyzes the output to verify mesh quality.

Checks performed by the injected snippet:
  - Non-manifold edges (non-watertight mesh → slicer rejects it)
  - Loose vertices (free vertices, Boolean residue)
  - Degenerate faces (faces with area ≈ 0)
  - Zero volume (flat or empty mesh)
  - No mesh objects in the scene
"""

from __future__ import annotations
from typing import Tuple, List


_VALIDATION_SNIPPET = '''

import bmesh as _bmesh

_val_issues: list = []
_mesh_objs = [_o for _o in bpy.data.objects if _o.type == "MESH"]

if not _mesh_objs:
    _val_issues.append("NO_MESH_OBJECTS")
else:
    _depsgraph = bpy.context.evaluated_depsgraph_get()

    for _obj in _mesh_objs:
        _eval = _obj.evaluated_get(_depsgraph)
        _mesh_eval = _eval.to_mesh()

        _bm = _bmesh.new()
        _bm.from_mesh(_mesh_eval)
        _bm.verts.ensure_lookup_table()
        _bm.edges.ensure_lookup_table()
        _bm.faces.ensure_lookup_table()

        _nm = [_e for _e in _bm.edges if not _e.is_manifold]
        if _nm:
            _val_issues.append(f"NON_MANIFOLD_EDGES:{_obj.name}:{len(_nm)}")

        _lv = [_v for _v in _bm.verts if not _v.link_edges]
        if _lv:
            _val_issues.append(f"LOOSE_VERTS:{_obj.name}:{len(_lv)}")

        _zf = [_f for _f in _bm.faces if _f.calc_area() < 1e-10]
        if _zf:
            _val_issues.append(f"DEGENERATE_FACES:{_obj.name}:{len(_zf)}")

        _vol = _bm.calc_volume()
        if _vol < 1e-12:
            _val_issues.append(f"ZERO_VOLUME:{_obj.name}")

        _bm.free()
        _eval.to_mesh_clear()

if _val_issues:
    print("MESH_VALIDATION_FAIL:" + "|".join(_val_issues))
else:
    print(f"MESH_VALIDATION_OK:checked_{len(_mesh_objs)}_objects")
'''


class MeshValidator:
    """Validates the mesh generated by a Blender script.

    Injects a bmesh snippet that checks manifoldness, loose
    vertices, degenerate faces, volume, and presence of mesh objects.
    The result is used by the orchestrator to decide whether to proceed
    to the next phase or iterate the fix.

    Args:
        runner: BlenderRunner instance for execution.
    """

    def __init__(self, runner) -> None:
        self.runner = runner

    async def validate(self, script: str) -> Tuple[bool, List[str]]:
        """Injects the snippet, executes in Blender, analyzes output.

        Args:
            script: Blender script to validate (without snippet).

        Returns:
            (True, []) if the mesh is valid.
            (False, [issues...]) if there are geometric problems.
        """
        combined = script + _VALIDATION_SNIPPET

        success, output = await self.runner.execute(combined)

        if not success:
            last_line = output.splitlines()[-1] if output else "output vuoto"
            return False, [f"EXEC_FAILED_DURING_VALIDATION:{last_line}"]

        for line in output.splitlines():
            line = line.strip()
            if line.startswith("MESH_VALIDATION_OK"):
                return True, []
            if line.startswith("MESH_VALIDATION_FAIL:"):
                raw = line.replace("MESH_VALIDATION_FAIL:", "")
                return False, [i for i in raw.split("|") if i]

        return False, ["VALIDATION_MARKERS_NOT_FOUND_IN_OUTPUT"]

    @staticmethod
    def format_issues_for_llm(issues: List[str]) -> str:
        """Converts validation issues into an LLM-readable report.

        Args:
            issues: List of issue code strings (e.g. NON_MANIFOLD_EDGES:obj:5).

        Returns:
            Formatted text with detailed descriptions for each issue.
        """
        lines = ["MESH VALIDATION REPORT (issues preventing 3D printing):"]
        for issue in issues:
            if issue.startswith("NON_MANIFOLD_EDGES"):
                _, obj, count = issue.split(":")
                lines.append(
                    f"  NON-MANIFOLD: '{obj}' has {count} open edges. "
                    "The mesh is not watertight -> slicer will reject it or produce failed prints."
                )
            elif issue.startswith("LOOSE_VERTS"):
                _, obj, count = issue.split(":")
                lines.append(
                    f"  LOOSE VERTS: '{obj}' has {count} unconnected vertices. "
                    "Residue from Boolean operations. Fix: bmesh.ops.delete + dissolve."
                )
            elif issue.startswith("DEGENERATE_FACES"):
                _, obj, count = issue.split(":")
                lines.append(
                    f"  DEGENERATE FACES: '{obj}' has {count} faces with area ~= 0. "
                    "Fix: Weld modifier or bmesh.ops.remove_doubles."
                )
            elif issue.startswith("ZERO_VOLUME"):
                parts = issue.split(":", 1)
                obj = parts[1] if len(parts) > 1 else ""
                lines.append(
                    f"  ZERO VOLUME: '{obj}' has no real volume. "
                    "Mesh is likely flat or empty."
                )
            elif issue == "NO_MESH_OBJECTS":
                lines.append(
                    "  NO MESH OBJECTS in the scene. "
                    "The script finished without creating geometry."
                )
            elif issue.startswith("EXEC_FAILED"):
                lines.append(f"  CRASH DURING VALIDATION: {issue}")
            else:
                lines.append(f"  {issue}")
        return "\n".join(lines)
